/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ca2;

import com.mysql.cj.xdevapi.Statement;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sebastian fernandes
 */
public class Forgot extends javax.swing.JFrame {

    /**
     * Creates new form Forgot
     */
    public Forgot() {
        initComponents();
        Submit.setEnabled(false);
        email.setEnabled(false);
        Pwrdl.setEnabled(false);
         var toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Uname = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        Pwrdl = new javax.swing.JPasswordField();
        Submit = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(121, 155, 4));
        jPanel1.setPreferredSize(new java.awt.Dimension(616, 334));

        Uname.setBackground(new java.awt.Color(170, 182, 128));
        Uname.setForeground(new java.awt.Color(102, 102, 102));
        Uname.setText("Username");
        Uname.setBorder(null);
        Uname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UnameFocusLost(evt);
            }
        });

        search.setBackground(new java.awt.Color(32, 46, 23));
        search.setForeground(new java.awt.Color(220, 219, 219));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        email.setBackground(new java.awt.Color(170, 182, 128));
        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setBorder(null);

        Pwrdl.setBackground(new java.awt.Color(170, 182, 128));
        Pwrdl.setForeground(new java.awt.Color(102, 102, 102));
        Pwrdl.setBorder(null);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Pixle_Font", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 213, 174));
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Pixle_Font", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 213, 174));
        jLabel2.setText("Email Address:");

        jLabel3.setFont(new java.awt.Font("Pixle_Font", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 213, 174));
        jLabel3.setText("New Password:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pwrdl, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Submit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                .addComponent(Cancel))
                            .addComponent(Uname))
                        .addGap(18, 18, 18)
                        .addComponent(search)
                        .addGap(120, 120, 120))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Uname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pwrdl, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit)
                    .addComponent(Cancel))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       try{
           System.out.println("\n Okay this thing is done");
       String username = Uname.getText();
       String password =String.valueOf(Pwrdl.getPassword()) ;
       
       String sql = "select * from game where username=? ";
       
       
       
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","");
       PreparedStatement pst= conn.prepareStatement(sql);
       pst.setString(1,username);
          
          
       ResultSet r = pst.executeQuery();
          
          if(r.next()){
                        JOptionPane.showMessageDialog(null, "Welcome " +username);
//                        dispose();
//                        Menu menu = new Menu();
//                        String name =Uname.getText();
//                         new Menu(name).setVisible(true);
//         WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
                 Submit.setEnabled(true);
                 email.setEnabled(true);
                 Pwrdl.setEnabled(true);
     
          }
          else{
          
            JOptionPane.showMessageDialog(null, "Try again");
          Uname.setText("");
         Uname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
          }
       }catch(HeadlessException | SQLException e){
}
    }//GEN-LAST:event_searchActionPerformed

    private void UnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UnameFocusGained
     Uname.setBorder(null);
         
         if(Uname.getText().equals("Username")){
         Uname.setText("");
        
         }
    }//GEN-LAST:event_UnameFocusGained

    private void UnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UnameFocusLost
                Uname.setBorder(null);
        
        if(Uname.getText().trim().isEmpty()){
        Uname.setText("Username");
        
        Uname.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_UnameFocusLost

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();
                        

                        new Login().setVisible(true);
         WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    }//GEN-LAST:event_CancelActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
       String username = Uname.getText();
       String Email = email.getText();
       String password =String.valueOf(Pwrdl.getPassword()) ;
       
        System.out.println(password);
       try{
       
       String sql = "select * from game where username='"+username+"' and email='"+Email+"'";
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","");
           java.sql.Statement pst= conn.createStatement();
       
      System.out.println("Done!");
//       Statement pst= (Statement) conn.createStatement();
       ResultSet rs = pst.executeQuery(sql);
       
     
     
      
       if(rs.next()){
             int num = rs.getInt("ID");
      
      System.out.println(num);
           System.out.println("Done!!!!");
           sql ="update game set password='"+password+"' where ID = '"+num+"'  ";
          conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","");
           PreparedStatement p = conn.prepareStatement(sql);
        p.executeUpdate();
        System.out.println("Done!!!!");
        JOptionPane.showMessageDialog(null,"Password reset succssfully!");
                     dispose();
        new Login().setVisible(true);
         WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
       }
       else{
       JOptionPane.showMessageDialog(null,"Something went wrong\nTry again later");
       }
       
       }catch(SQLException e){}
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JPasswordField Pwrdl;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField Uname;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
