/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ca2;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.*;

// import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sebastian fernandes
 */
public final class leaderboard extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public leaderboard() {
        initComponents();
        fatch();  
    var toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);}
    
 public leaderboard(String Uname) {
        initComponents();
        display.setText(Uname);
         fatch();   
         var toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JLabel();
        Messed = new javax.swing.JPanel();
        EAsy = new javax.swing.JButton();
        HArd = new javax.swing.JButton();
        VEteran = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        display.setText("display");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Messed.setBackground(new java.awt.Color(121, 155, 4));
        Messed.setPreferredSize(new java.awt.Dimension(616, 334));
        Messed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EAsy.setBackground(new java.awt.Color(32, 46, 23));
        EAsy.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        EAsy.setForeground(new java.awt.Color(220, 219, 219));
        EAsy.setText("Easy");
        EAsy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EAsyMouseClicked(evt);
            }
        });
        EAsy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EAsyActionPerformed(evt);
            }
        });
        EAsy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EAsyKeyPressed(evt);
            }
        });
        Messed.add(EAsy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, -1));

        HArd.setBackground(new java.awt.Color(32, 46, 23));
        HArd.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        HArd.setForeground(new java.awt.Color(220, 219, 219));
        HArd.setText("Hard");
        HArd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HArdActionPerformed(evt);
            }
        });
        Messed.add(HArd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, -1));

        VEteran.setBackground(new java.awt.Color(32, 46, 23));
        VEteran.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        VEteran.setForeground(new java.awt.Color(220, 219, 219));
        VEteran.setText("Veteran");
        VEteran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEteranActionPerformed(evt);
            }
        });
        Messed.add(VEteran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, -1));

        jButton4.setBackground(new java.awt.Color(32, 46, 23));
        jButton4.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(220, 219, 219));
        jButton4.setText("Messed");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Messed.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, -1));

        jButton5.setBackground(new java.awt.Color(32, 46, 23));
        jButton5.setFont(new java.awt.Font("pixel dead", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(220, 219, 219));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Messed.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 239, -1, -1));

        jTabbedPane1.setBackground(new java.awt.Color(121, 155, 4));

        jPanel2.setBackground(new java.awt.Color(121, 155, 4));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(121, 155, 4));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(121, 155, 4));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab3", jPanel4);

        jPanel1.setBackground(new java.awt.Color(121, 155, 4));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setPreferredSize(new java.awt.Dimension(225, 80));
        jScrollPane2.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab4", jPanel1);

        Messed.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -40, 470, 340));

        getContentPane().add(Messed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        public void fatch(){
       jTabbedPane1.setSelectedIndex(0);
    
                          try{
            
         System.out.println("\n Okay this thing is done");
               Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","");
               
                  System.out.println("\n Okay this thing is done");
               
               
                  String sql = "SELECT `ID`, `username`, `easy` FROM `game`"; 
                       PreparedStatement pst= conn.prepareStatement(sql);
      System.out.println("\n Okay this thing is done");       
                  ResultSet r = pst.executeQuery();
                  jTable2.setModel(DbUtils.resultSetToTableModel(r));
              System.out.println("\n Okay this thing is done");
        }
            catch(SQLException e){
}   

    
    }
    
    
    
    
    
    private void EAsyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EAsyActionPerformed
     
 fatch();    
 
 
 
    }//GEN-LAST:event_EAsyActionPerformed

    private void HArdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HArdActionPerformed
        // TODO add your handling code here:
jTabbedPane1.setSelectedIndex(1);
       
                          try{
            
         System.out.println("\n Okay this thing is done");
               Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","");
               
                  System.out.println("\n Okay this thing is done");
               
               
                  String sql = "SELECT `ID`, `username`, `hard` FROM `game`"; 
                       PreparedStatement pst= conn.prepareStatement(sql);
      System.out.println("\n Okay this thing is done");       
                  ResultSet r = pst.executeQuery();
                  jTable1.setModel(DbUtils.resultSetToTableModel(r));
              System.out.println("\n Okay this thing is done");
        }
            catch(SQLException e){
}   
            

    }//GEN-LAST:event_HArdActionPerformed

    private void VEteranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEteranActionPerformed
        // TODO add your handling code here:
jTabbedPane1.setSelectedIndex(2);
   
            
                      try{
            
         System.out.println("\n Okay this thing is done");
               Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","");
               
                  System.out.println("\n Okay this thing is done");
               
               
                  String sql = "SELECT `ID`, `username`, `Veteran` FROM `game`"; 
                       PreparedStatement pst= conn.prepareStatement(sql);
      System.out.println("\n Okay this thing is done");       
                  ResultSet r = pst.executeQuery();
                  jTable4.setModel(DbUtils.resultSetToTableModel(r));
              System.out.println("\n Okay this thing is done");
        }
            catch(SQLException e){
}   

   
    }//GEN-LAST:event_VEteranActionPerformed

    private void EAsyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EAsyKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_EAsyKeyPressed

    private void EAsyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EAsyMouseClicked
        // TODO add your handling code here:
        
   
        
    }//GEN-LAST:event_EAsyMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String Uname = display.getText();
        dispose();
        new Menu(Uname).setVisible(true);
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTabbedPane1.setSelectedIndex(3);
   
            
                      try{
            
         System.out.println("\n Okay this thing is done");
               Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","");
               
                  System.out.println("\n Okay this thing is done23332");
               
               
                  String sql = "SELECT `ID`, `username`, `Messed` FROM `game`"; 
                       PreparedStatement pst= conn.prepareStatement(sql);
      System.out.println("\n Okay this thing is done4485");       
      
                  ResultSet r = pst.executeQuery();
                  jTable3.setModel(DbUtils.resultSetToTableModel(r));
              System.out.println("\n Okay this thing is don757575e");
        }
            catch(SQLException e){
}   

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new leaderboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EAsy;
    private javax.swing.JButton HArd;
    private javax.swing.JPanel Messed;
    private javax.swing.JButton VEteran;
    private javax.swing.JLabel display;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
