/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ca2;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.*;

// import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sebastian fernandes
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        var toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
    }
DBConnnection conn = new DBConnnection();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Login = new javax.swing.JButton();
        Uname = new javax.swing.JTextField();
        show_validation = new javax.swing.JTextField();
        Pwrdl = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        toggle = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(121, 155, 4));
        jPanel1.setPreferredSize(new java.awt.Dimension(616, 334));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        Login.setBackground(new java.awt.Color(32, 46, 23));
        Login.setFont(new java.awt.Font("Pixle_Font", 0, 24)); // NOI18N
        Login.setForeground(new java.awt.Color(220, 219, 219));
        Login.setText("Login");
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        Uname.setBackground(new java.awt.Color(170, 182, 128));
        Uname.setForeground(new java.awt.Color(102, 102, 102));
        Uname.setText("Username/Email");
        Uname.setBorder(null);
        Uname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UnameFocusLost(evt);
            }
        });
        Uname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UnameKeyTyped(evt);
            }
        });

        show_validation.setBackground(new java.awt.Color(121, 155, 4));
        show_validation.setBorder(null);
        show_validation.setFocusable(false);

        Pwrdl.setBackground(new java.awt.Color(170, 182, 128));
        Pwrdl.setForeground(new java.awt.Color(102, 102, 102));
        Pwrdl.setText("********");
        Pwrdl.setBorder(null);
        Pwrdl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PwrdlFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PwrdlFocusLost(evt);
            }
        });
        Pwrdl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PwrdlKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PwrdlKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Pixle_Font", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 213, 174));
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Pixle_Font", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 213, 174));
        jLabel2.setText("Password:");

        toggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca2/icons8-hide-32.png"))); // NOI18N
        toggle.setContentAreaFilled(false);
        toggle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toggle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleMouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Forgot password?");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Do not have an account?");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 153));
        jLabel5.setText("Signup");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Uname, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Pwrdl, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggle))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(show_validation, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Uname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toggle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pwrdl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(show_validation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        char[] pass = Pwrdl.getPassword();
           if(Uname.getText().equals("Username/Email") && pass.equals("********")){
            show_validation.setText("Field(s) are empty");
            Uname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
            Pwrdl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
            
            
        }
        else if(Uname.getText().equals("Username/Email")){
             show_validation.setText("Username/Email is required ");
             Uname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        }
        else if(pass.equals("********")){
          show_validation.setText("Password is required ");
          Pwrdl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        }
      else if(Uname.getText().equals("Shelton") || (Uname.getText().equals("macbookf1566@gmail.com")) && Pwrdl.getPassword().equals("chowgules") ){
    JOptionPane.showMessageDialog(null,"Welcome back");
    Uname.setText("");
    Pwrdl.setText("");
    }
        else {
         show_validation.setText("");
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        // TODO add your handling code here:
        
        
         try{
           System.out.println("\n Okay this thing is done");
       String username = Uname.getText();
       String password =String.valueOf(Pwrdl.getPassword()) ;
       
       String sql = "select * from game where username=? and password=?";
       
       
       
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","");
       PreparedStatement pst= conn.prepareStatement(sql);
       pst.setString(1,username);
          pst.setString(2,password); 
          
       ResultSet r = pst.executeQuery();
          
          if(r.next()){
                        JOptionPane.showMessageDialog(null, "Welcome " +username);
                        dispose();
                        Menu menu = new Menu();
                        String name =Uname.getText();
                         new Menu(name).setVisible(true);
         WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
     
          }
          else{
          
              int check = JOptionPane.showConfirmDialog(null,"Username not found \n Create new account or try again","Not found",JOptionPane.YES_NO_OPTION);
              if(check==0){
                  dispose();
                  new Register().setVisible(true);
         WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
              }
              else{
                 JOptionPane.showMessageDialog(null, "Try again");
          Uname.setText("");
          Pwrdl.setText("");
              }
              
         
          }
       }catch(HeadlessException | SQLException e){
}
        
    }//GEN-LAST:event_LoginMouseClicked

    private void PwrdlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PwrdlKeyPressed
        // TODO add your handling code here:
        char[] pass = Pwrdl.getPassword();
        if(Uname.getText().equals("Username/Email") && pass.equals("********")){
            show_validation.setText("Field(s) are empty");
            Uname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
            Pwrdl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
            
            
        }
        else if(Uname.getText().equals("Username/Email")){
             show_validation.setText("Username/Email is required ");
             Uname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        }
        else if(pass.equals("********")){
          show_validation.setText("Password is required ");
          Pwrdl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        }
      else if(Uname.getText().equals("Shelton") || (Uname.getText().equals("macbookf1566@gmail.com")) && Pwrdl.getPassword().equals("chowgules") ){
    JOptionPane.showMessageDialog(null,"Welcome back");
    Uname.setText("");
    Pwrdl.setText("");
    }
        else {
         show_validation.setText("");
        }
        
        
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
         try{
           System.out.println("\n Okay this thing is done");
       String username = Uname.getText();
       String password =String.valueOf(Pwrdl.getPassword()) ;
       
       String sql = "select * from game where username=? and password=?";
       
       
       
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","");
       PreparedStatement pst= conn.prepareStatement(sql);
       pst.setString(1,username);
          pst.setString(2,password); 
          
       ResultSet r = pst.executeQuery();
          
          if(r.next()){
                        JOptionPane.showMessageDialog(null, "Welcome " +username);
                        dispose();
                        Menu menu = new Menu();
                        String name =Uname.getText();
                         new Menu(name).setVisible(true);
         WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
     
          }
          else{
          
            JOptionPane.showMessageDialog(null, "Try again");
          Uname.setText("");
          Pwrdl.setText("");
          }
       }catch(HeadlessException | SQLException e){
}
        
        }
    }//GEN-LAST:event_PwrdlKeyPressed

    private void PwrdlFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PwrdlFocusGained
        // TODO add your handling code here:
          char[] pass = Pwrdl.getPassword();
          Pwrdl.setBorder(null);
       if(pass.equals("********"))
       Pwrdl.setText("");
    }//GEN-LAST:event_PwrdlFocusGained

    private void PwrdlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PwrdlFocusLost
        Pwrdl.setBorder(null);
        char[] pass = Pwrdl.getPassword();
       if(pass==null){
        Pwrdl.setText("********");
        Pwrdl.setForeground(new Color(102,102,102));
       }
    }//GEN-LAST:event_PwrdlFocusLost

    private void UnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UnameFocusGained
        Uname.setBorder(null);
         
         if(Uname.getText().equals("Username/Email")){
         Uname.setText("");
        
         }
    }//GEN-LAST:event_UnameFocusGained

    private void UnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UnameFocusLost
               Uname.setBorder(null);
        
        if(Uname.getText().trim().isEmpty()){
        Uname.setText("Username/Email");
        
        Uname.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_UnameFocusLost

    private void UnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UnameKeyTyped
        Uname.setForeground(new Color(116, 15, 43));
    }//GEN-LAST:event_UnameKeyTyped

    private void PwrdlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PwrdlKeyTyped
        Pwrdl.setForeground(new Color(116, 15, 43));
    }//GEN-LAST:event_PwrdlKeyTyped

    private void toggleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleMouseClicked
        if(toggle.isSelected()){
      toggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca2/icons8-hide-32.png"))); // NOI18N
 
       
        Pwrdl.setEchoChar((char)0);
        }
        else{
toggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca2/icons8-eye-32.png"))); // NOI18N
        Pwrdl.setEchoChar('*');
        }
    }//GEN-LAST:event_toggleMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
       dispose();
                     
                        new Forgot().setVisible(true);
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        dispose();      
        new Register().setVisible(true);
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    }//GEN-LAST:event_jLabel5MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JPasswordField Pwrdl;
    private javax.swing.JTextField Uname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField show_validation;
    private javax.swing.JToggleButton toggle;
    // End of variables declaration//GEN-END:variables
}
