/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ca2;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.*;

// import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sebastian fernandes
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        var toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
    }
DBConnnection conn = new DBConnnection();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Uname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        Pwrdl = new javax.swing.JPasswordField();
        Signup = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        show_validation = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Pixle_Font", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 213, 174));
        jLabel1.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Pixle_Font", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 213, 174));
        jLabel3.setText("Email Address:");

        jLabel5.setFont(new java.awt.Font("Pixle_Font", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 213, 174));
        jLabel5.setText("New Password:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(121, 155, 4));
        jPanel1.setPreferredSize(new java.awt.Dimension(616, 334));

        Uname.setBackground(new java.awt.Color(170, 182, 128));
        Uname.setForeground(new java.awt.Color(102, 102, 102));
        Uname.setBorder(null);

        email.setBackground(new java.awt.Color(170, 182, 128));
        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setBorder(null);

        Pwrdl.setBackground(new java.awt.Color(170, 182, 128));
        Pwrdl.setForeground(new java.awt.Color(102, 102, 102));
        Pwrdl.setText("********");
        Pwrdl.setBorder(null);

        Signup.setBackground(new java.awt.Color(32, 46, 23));
        Signup.setFont(new java.awt.Font("Pixle_Font", 0, 20)); // NOI18N
        Signup.setForeground(new java.awt.Color(220, 219, 219));
        Signup.setText("Signup");
        Signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupMouseClicked(evt);
            }
        });
        Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Pixle_Font", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 213, 174));
        jLabel2.setText("Username:");

        jLabel4.setFont(new java.awt.Font("Pixle_Font", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 213, 174));
        jLabel4.setText("Email Address:");

        jLabel6.setFont(new java.awt.Font("Pixle_Font", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 213, 174));
        jLabel6.setText("Password:");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Already have any account?");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setText("Login");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        show_validation.setBackground(new java.awt.Color(121, 155, 4));
        show_validation.setForeground(new java.awt.Color(255, 204, 204));
        show_validation.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Signup)
                                .addGap(22, 22, 22)))
                        .addComponent(jLabel8))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Uname)
                    .addComponent(jLabel4)
                    .addComponent(Pwrdl)
                    .addComponent(email)
                    .addComponent(jLabel6)
                    .addComponent(show_validation, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                .addGap(44, 209, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(Pwrdl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(show_validation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Signup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupActionPerformed
        // TODO add your handling code here:
                char[] pass = Pwrdl.getPassword();
            if(Uname.getText().equals("") && pass.equals("********") && email.getText().equals("")){
            show_validation.setText("Field(s) are empty");
            Uname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
            Pwrdl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
            email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
            
        }
        else if(Uname.getText().equals("")){
             show_validation.setText("Username is required ");
             Uname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        }
       
        else if(email.getText().equals("")){
         email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
         show_validation.setText("Email is required ");
        }
        
         else if(pass.equals("********")){
          show_validation.setText("Password is required ");
          Pwrdl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        }
      else if(Uname.getText().equals("Shelton") && (email.getText().equals("macbookf1566@gmail.com")) && Pwrdl.getPassword().equals("chowgules") ){
    JOptionPane.showMessageDialog(null,"Welcome back");
    Uname.setText("");
    Pwrdl.setText("");
    }
        else {
         show_validation.setText("");
        }
    }//GEN-LAST:event_SignupActionPerformed

    private void SignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupMouseClicked
        // TODO add your handling code here:
        if(show_validation.getText().equals("")){
                 try{
           System.out.println("\n Okay this thing is done");
       String username = Uname.getText();
       String password =String.valueOf(Pwrdl.getPassword()) ;
       
    String sql = "select * from game where username=? or email=? and password=?";

       
       
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","");
       PreparedStatement pst= conn.prepareStatement(sql);
       pst.setString(1,username);
       pst.setString(2, email.getText());
       pst.setString(3,password); 
          
       ResultSet r = pst.executeQuery();
          
          if(r.next()){
                        JOptionPane.showMessageDialog(null, "This username/email already exists \n Please login");
                        dispose();
                     
                         new Login().setVisible(true);
         WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
     
          }
          
          else{
          
 try{
     
        String Email= email.getText();
        String pass =String.valueOf(Pwrdl.getPassword()) ;
       conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","");
      String sql1 ="INSERT INTO `game`(username,email,password) VALUES ('"+username+"','"+Email+"','"+pass+"') ";
//      Statement pst = conn.createStatement();
     
      pst.executeUpdate(sql1);
      JOptionPane.showMessageDialog(null,"Welcome "+username);
      dispose();
                        Menu menu = new Menu();
                         
                         String name =Uname.getText();
                         new Menu(name).setVisible(true);
         WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
      
          }catch(Exception e){
    System.out.println(e);}
          
          
          
          
          }
          
                          
          
          
       }catch(HeadlessException | SQLException e){
}
        }
        
        

    }//GEN-LAST:event_SignupMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
             dispose();
                     
                         new Login().setVisible(true);
         WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Pwrdl;
    private javax.swing.JButton Signup;
    private javax.swing.JTextField Uname;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField show_validation;
    // End of variables declaration//GEN-END:variables
}
